### ISSUE TITLE
Suggestions for Tv series 

### ISSUE THREAD

**Issue by 4face-studi0** [4face-studi0/CineScout#80]

**Comment by XelaAl** [comment]
Here is my list of suggestions:
The Crown
Ozark
Unorthodox 
The Society
The OA
Designated Survivor
Madmen
Peaky Blinders
The Stranger
American Crime Story
Also, I've just finished watching The Last Dance. I should say, this docuseries turned out to be brilliant. As I like basketball, it was very interesting to found out more about one of the greatest teams (the Chicago Bulls) and one of the most brilliant players (Michael Jordan). I really liked the docuseries. It is worth watching.
